version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: marketing_nbp_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: marketing_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_this_password}
      POSTGRES_DB: marketing_nbp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - marketing_network

  # Redis for Background Jobs
  redis:
    image: redis:7-alpine
    container_name: marketing_nbp_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-change_this_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - marketing_network

  # Next.js Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketing_nbp_web
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://marketing_user:${DB_PASSWORD:-change_this_password}@postgres:5432/marketing_nbp?schema=public
      REDIS_URL: redis://:${REDIS_PASSWORD:-change_this_password}@redis:6379
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions
    networks:
      - marketing_network

  # Background Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: marketing_nbp_worker
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://marketing_user:${DB_PASSWORD:-change_this_password}@postgres:5432/marketing_nbp?schema=public
      REDIS_URL: redis://:${REDIS_PASSWORD:-change_this_password}@redis:6379
      NODE_ENV: production
    volumes:
      - ./sessions:/app/sessions
    networks:
      - marketing_network

volumes:
  postgres_data:
  redis_data:

networks:
  marketing_network:
    driver: bridge
